name: 'Build frontend'
author: 'IhateTrains'
branding:
  icon: 'layout'
  color: 'orange'
description: 'Build frontend for a ParadoxGameConverters converter'
inputs:
  msbuild_path:
    description: '[Only required for Windows] Path to MSBuild.exe'
    required: true
    default: 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/MSBuild.exe'
  build_ConverterFrontend:
    description: 'Whether to build ConverterFrontend'
    default: true
  build_updater:
    description: 'Whether to build updater'
    default: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        MSBUILD_PATH: ${{ inputs.msbuild_path }}
        BUILD_CONVERTERFRONTEND: ${{ inputs.build_ConverterFrontend }}
        BUILD_UPDATER: ${{ inputs.build_updater }}
      run: |
        script_path=`echo "${{ github.action_path }}/entrypoint.sh" | sed "s,\\,/,"`
        bash script_path
